# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeSAC-Friends' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeSAC-Friends
  pod 'Firebase/Auth'
  pod 'SnapKit', '~> 5.0.0'
  pod 'R.swift'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  
  target 'SeSAC-FriendsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeSAC-FriendsUITests' do
    # Pods for testing
  end

end
